server.port=8080

spring.application.name=reframe

# RDS (PostgreSQL) 接続設定
spring.datasource.url=jdbc:postgresql://db-reframe-dev.c38au42gu20l.ap-northeast-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=a2hW2X87
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate 設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true